services:
  postgres:
    image: postgres:16-alpine3.22
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PasswordForPostgres
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:8.2.1
    container_name: inventory-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  pgadmin:
    image: dpage/pgadmin4:9.8.0
    container_name: inventory-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: PasswordForPgadmin
    ports:
      - "5050:80"

volumes:
  postgres_data:
  redis_data: